"""add question table

Revision ID: ebca14f6087d
Revises: 9068493b04d4
Create Date: 2025-09-05 14:43:26.503313

"""

from typing import Sequence, Union

import sqlalchemy as sa

import models
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ebca14f6087d"
down_revision: Union[str, Sequence[str], None] = "9068493b04d4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "interview_questions",
        sa.Column("id", models.UUID(length=36), nullable=False),
        sa.Column("interview_id", models.UUID(length=36), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("welcome_text", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["interview_id"],
            ["interviews.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("interview_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("interview_questions")
    # ### end Alembic commands ###
